image: ruby:2.1.7

pipelines:
  default:
    - step:
        script:
          - bundler --version
          - bundle install
          - bundle exec jekyll build
  branches:
    master:
      - step:
          script:
            - bundler --version
            - bundle install
            - bundle exec jekyll build
            - apt-get update
            - apt-get -qq install lftp
            - lftp -c "open -u $FTP_USER_PRODUCTION,$FTP_PASSWORD_PRODUCTION ftp4.multinexo.com; set ssl:verify-certificate no; mirror -R --delete-first -v ./_site /"
            - curl -X DELETE "https://api.cloudflare.com/client/v4/zones/ab8c0e9c04ee891c6ae55923b7b9d4ea/purge_cache" -H "$CLOUDFLARE_X_AUTH_EMAIL" -H "$CLOUDFLARE_X_AUTH_KEY" -H "$CLOUDFLARE_CONTENT_TYPE" --data '{"purge_everything":true}'
