version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1
    steps:
      - checkout
      - run:
          name: Clone dev-docs-base
          command: git clone https://github.com/reyesoft/dev-docs-base.git && cp -r ./dev-docs-base/* .
      - run:
          name: Install dependencies
          command: bundle install
      - run:
          name: Build project
          command: bundle exec jekyll build
  deploy-to-ghpages:
    docker:
      - image: circleci/ruby:2.5.1
    steps:
      - checkout
      - run:
          name: Clone dev-docs-base
          command: git clone https://github.com/reyesoft/dev-docs-base.git && cp -r ./dev-docs-base/* .
      - run:
          name: Install dependencies
          command: bundle install
      - run:
          name: Build project
          command: bundle exec jekyll build
      - run:
          name: Publish to Github Pages
          command: bundle exec jgd -r some-branch-that-will-never-exist-in-this-repo
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore: v2.0
  deploy:
    jobs:
      - deploy-to-ghpages:
          filters:
            branches:
              only: v2.0
